language: python
python:
  - "2.6"
  - "2.7"
install:                                                                                                                                                                                                                            
  - pip install numpy                                                                                                                                                                                                               
  - pip install matplotlib
  - pip install netCDF4
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests
