#hacked from:
#http://conda.pydata.org/docs/travis.html
#https://github.com/xray/xray/blob/master/.travis.yml

notifications:
  email:
    recipients:
      - christopher.y.bull@student.unsw.edu.au
    on_success: change # default: change
    on_failure: always # default: always
before_script: "sudo aptitude -y -q install ffmpeg"
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.5"
#Hiro Asari's advice for git-lfs
before_install:
  - wget https://github.com/github/git-lfs/releases/download/v1.1.0/git-lfs-linux-amd64-1.1.0.tar.gz
  - tar -zxvf git-lfs-linux-amd64-1.1.0.tar.gz
  - export PATH=`pwd`/git-lfs-1.1.0:$PATH
  - "git lfs install"
  - "git lfs pull"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib netCDF4
  - source activate test-environment
#  - python setup.py install

script:
  - python mkmov.py zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 -o $(pwd)/zos_example.mov zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 --fps 10 zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 --fps 10 --cmap jet zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 --fps 10 --cmap autumn --clev 60 zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 --figwth 10 --fighgt 12 zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --min -1 --max 1 --lmask 0 --figwth 10 --fighgt 12 --killsplash zos examples/cordex24-ERAI01_1d_20040101_20040111_grid_T_2D.nc
  - python mkmov.py --stitch -o $(pwd)/stitchmov.mov $(pwd)/examples/StitchMePlots/*.png
  - python mkmov.py --stitch -o $(pwd)/stitchmov2.mov --fps 10 $(pwd)/examples/StitchMePlots/*.png
  - python mkmov.py --stitch -o $(pwd)/stitchmov2.mov --fps 10 --killsplash $(pwd)/examples/StitchMePlots/*.png

#download more examples
  - git clone https://github.com/chrisb13/mkmovexamples.git $(pwd)/mkmovexamples
  
  - python mkmov.py adt --lmask -214748 --cmap Set3 -o $(pwd)/AVISOdt_global_allsat_madt_Set3.mov $(pwd)/mkmovexamples/aviso_madt/*.nc 
  - python mkmov.py adt --lmask -214748 --x lon --y lat --cmap Accent -o $(pwd)/AVISOdt_global_allsat_madt_Accent.mov $(pwd)/mkmovexamples/aviso_madt/*.nc 
  - python mkmov.py PV --fps 10 --fighgt 2.5 --figwth 14  -o  $(pwd)/avemom6PV_toplayer.mov $(pwd)/mkmovexamples/mom6/ave_prog__0006_016.nc
  - python mkmov.py PV --fps 10 --4dvar 1 -o  $(pwd)/avemom6PV_bottomlayer.mov $(pwd)/mkmovexamples/mom6/ave_prog__0006_016.nc
